### ISSUE TITLE
Can't set VM's net config (and some other option)

### ISSUE THREAD

**Issue by Jlan45** [luthermonson/go-proxmox#114]

**Comment by Jlan45** [comment]
<img width="299" alt="截屏2024-02-09 00 56 12" src="https://github.com/luthermonson/go-proxmox/assets/49506020/c11361ba-a92a-45a2-a20e-f42a4150295f">
As you see in this picture, the net params should be requested with list in http, but the VirtualMachineOption didn't give us options like "list" , so the Config action will fail and return bad request: 400 Parameter verification failed. - {"net[0]":"property is not defined in schema and the schema does not allow additional properties"}
(This may be caused by URL encoding.)
But I think it may be a good solution to directly use parameters similar to those in VirtualMachineConfig and process them in functions.

**Comment by jqueuniet** [comment]
The config key is `net0`, not `net[0]`.

ie: 

```go
vifopt := proxmox.VirtualMachineOption{
    Name:  fmt.Sprintf("net%d", vif.Index),
    Value: "virtio,bridge=" + vnet.GetInterfaceName(),
}
```

And there are already parameters for interfaces in the `VirtualMachineConfig`, with the same helpers as other similar indexed devices like disks.

```go
type VirtualMachineConfig struct {
        // [...]
        
	// Network devices
	Nets map[string]string `json:"-"`
	Net0 string            `json:"net0,omitempty"`
	Net1 string            `json:"net1,omitempty"`
	Net2 string            `json:"net2,omitempty"`
	Net3 string            `json:"net3,omitempty"`
	Net4 string            `json:"net4,omitempty"`
	Net5 string            `json:"net5,omitempty"`
	Net6 string            `json:"net6,omitempty"`
	Net7 string            `json:"net7,omitempty"`
	Net8 string            `json:"net8,omitempty"`
	Net9 string            `json:"net9,omitempty"`
	
        // [...]
}
```

**Comment by Jlan45** [comment]
Thanks, my problem has been solved.
