### ISSUE TITLE
complete container support

### ISSUE THREAD

**Issue by xortim** [luthermonson/go-proxmox#118]
This looks like a really promising library, thank you for sharing it.

Looking over the PVE API and the functionality implemented in the library. I was thinking the following enhancements would be helpful:

* Implement `node.NewContainer()`
    * `POST` to [`/nodes/{node}/lxc`](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc)
* Add ContainerConfig struct
* Add ContainerConfig field to Container struct
* Update `node.Container()` to include `container.Config`

This shouldn't break the existing API and bring it in line with existing VirtualMachine behavior. It would also complete CRUD functionality for PVE containers.

**Comment by luthermonson** [comment]
i tried to abstract the complexities so most get/put/post/delete aren't much more than a couple lines. you'll do fine and we can fix anything after you put up a PR

**Comment by luthermonson** [comment]
@xortim i think someone beat you to it #126, closing this for now but feel free to open new ones if anything was missed
