### ISSUE TITLE
Release v0.2.0 is tagged with v0.1.2

### ISSUE THREAD

**Issue by rybnico** [luthermonson/go-proxmox#167]
The v0.2.0 release is tagged as v0.1.2. `go get github.com/luthermonson/go-proxmox` will install v0.1.2 (presumably with the v0.2.0 code).

**Comment by luthermonson** [comment]
ugh my bad, let me just delete them and fix it since we dont have release artifacts

**Comment by luthermonson** [comment]
there, v0.2.0 is created and v0.1.2 is deleted
