### ISSUE TITLE
VirtualMachine states are broken since removing QMPStatus conditions

### ISSUE THREAD

**Issue by rybnico** [luthermonson/go-proxmox#171]
The fix for #139 (#166) breaks some VirtualMachine state functions.

Since the value of `QMPStatus` is not taken into account, the following functions are no longer reliable:

* `IsRunning` returns `true` even if the VirtualMachine is paused.
* `IsPaused` returns `true` even if the VirtualMachine is running (my fix in #169 is wrong because there is no `paused` state).
* `IsStopped` returns `true` even if the VirtualMachine is hibernated.

See PR #170

**Comment by rybnico** [comment]
Fixed by #170 
@luthermonson Would you mind releasing a version with this fix?

**Comment by luthermonson** [comment]
sure let me do it now

**Comment by luthermonson** [comment]
https://github.com/luthermonson/go-proxmox/releases/tag/v0.2.1
