### ISSUE TITLE
Node：json: cannot unmarshal number 42268934144 into Go struct field Ksm.Ksm.Shared of type int

### ISSUE THREAD

**Issue by StormYudi** [luthermonson/go-proxmox#23]
Node：json: cannot unmarshal number 42268934144 into Go struct field Ksm.Ksm.Shared of type int

happens on: node, err := client.Node("xxxx")

It seems that the KSM shared value is too big..

**Comment by StormYudi** [comment]
#24

**Comment by luthermonson** [comment]
thanks for the PR!
