### ISSUE TITLE
argument issues with qemu Clone/MoveDisk and policy on API backward compatibility

### ISSUE THREAD

**Issue by jqueuniet** [luthermonson/go-proxmox#39]
Hi,

I'm having issues using this client implementation of qemu `Clone` and `MoveDisk`.

`MoveDisk` seems focused on moving disks between storage backends and forces the use of the optional `storage` parameter, whereas I would like to use it to move disks from one VM to another while keeping the same storage backend, for which I need the optional parameters `format`, `target-disk` and `target-vmid`.

`Clone` has similar issues and forces the usage of the `target` optional parameter even though it only works with shared storage backends. I'm using local ZFS pools with templates in the local filesystem, and thus needs the `full`, `storage` and `format` optional parameters instead.

I could do a PR implementing all this while keeping the current optional parameters, but as those methods are using hardcoded args, this either means duplicating methods or breaking API compatibility, and I would like to ask for opinions on this subject first.

**Comment by luthermonson** [comment]
`MoveDisk` does no justice to the move_disk api end point at all and i totally agree. maybe it can be rewritten by having a `MoveDIskOptions` which can just be passed as nil if you have none and use it if you need it? Move storage to that and make `disk` a mandatory string?

`Clone` also lacks some optionals doesn't it. Maybe the same thing? Make the newid mandatory and have a `CloneOptions` with the optional options and make it a pointer if you want to pass no params?

**Comment by jqueuniet** [comment]
Discussion resolved with PR #40
