### ISSUE TITLE
Use of StringOrUint/64

### ISSUE THREAD

**Issue by earentir** [luthermonson/go-proxmox#59]
Wouldn't it be easier to always convert to the Uint64 type ?

**Comment by luthermonson** [comment]
welp you would think so... but the API was returning 1234 and "1234" and interchanged them a lot so I opted for this method so you know what you were getting and normalized the proxmox api in the client. I'm open for other suggestions....

**Comment by earentir** [comment]
I have seen the API making funny replies but I assume on most  fields it would always be an int type, maybe just force the output per case ? if an int is expected then check before and cast as int etc.

**Comment by luthermonson** [comment]
that's what this does. this makes it so you dont have to make a custom unmarshaller for each type with a Uint64 that might accidently send a string but instead one unmarshaller for a StringOrUint64 takes care of your problem. When I wrote it at the time I couldn't think of anything better and thinking again about it... i can't think of anything better :/
