### ISSUE TITLE
rrddata Endpoint Support & Missing/Outdated Elements in various structs

### ISSUE THREAD

**Issue by MattBGP** [luthermonson/go-proxmox#84]
Hi there,

I was wondering if there is planning on implementing the rrddata Endpoint `/api2/json/nodes/pve/qemu/<vmid>/rrddata`
With that I also have another question, why is the VirtualMachine struct and several other structs that outdated? There are several elements missing. The Library still seems to be actively maintained and updated except for the described issue. Is this on purpose?

Thank you in advance! :)

**Comment by luthermonson** [comment]
I'm sure I wrote the vm stuff in 6.x and more have since come out. I'll give it a refresh, thanks for the input. RE the other end point, sure! Let me look at into it at the same time.

**Comment by luthermonson** [comment]
take a look at the PR and see if that will work for you

**Comment by MattBGP** [comment]
Hi, looks good, added remaining relevant fields and created #87
